### ISSUE TITLE
Не нажимается кнопка перепланировать

### ISSUE THREAD

**Issue by supremko** [supremko/aqa-patterns#1]
Скрин в момент ошибки:
![image](https://user-images.githubusercontent.com/505723/71232766-54eed100-2304-11ea-99d6-1c8c9fed06c7.png)
Подстроил сценарий так, чтобы он отобразил нотификацию о перепланировании встречи, но никак не получается нажать её.
Пробовал варианты поиска:
$("[data-test-id='replan-notification']").$("button").waitUntil(visible,1000).click();
$("[data-test-id='replan-notification']").$("button").shouldHave(exactText("Перепланировать")).click();
$("[data-test-id='replan-notification']").waitUntil(visible,1000).$("button").click();

**Comment by ArRomanov** [comment]
Если вы чуть подробнее исследуете дерево элементов, то вы можете увидеть, что у самой кнопки нет никакого текста, а текст "Перепланировать" находится во вложенном элементе `span`. Поэтому вы никак не можете дождаться элемента `button` с текстом "Перепланировать". Можете попробовать найти кнопку, а в ней уже искать элемент по тексту или сразу искать элемент `span` с необходимым текстом

**Comment by supremko** [comment]
Поменял на `replan.waitUntil(visible,1500).$("[class='button__content']").click();` все равно не нажимает, хотя чуть выше этот сценарий с уже видимой сразу кнопкой отрабатывает без проблем.
